global:
  dependencies:
    python:
      - forge-sdk==5.0.0b0
      - forge-cli==5.0.0b0
      # - cecs==4.0.0a3
      - services/*.py
  env:
    PROJECT_SLUG: "kaliopa"

    ENVIRONMENT_NAME: {{ env.CI_COMMIT_REF_SLUG }}
    MODULE: '{{ env.MODULE | default("local", True) }}'
    LOG_LEVEL: DEBUG

    # Messaging
    PULSAR_URL: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    COMPRESSION_TYPE: LZ4
    SUBSCRIPTION_TYPE: Shared
    SUBSCRIPTION_INITIAL_POSITION: Earliest

    # Databases
    MONGO_CLIENT_HOST: mongodb:27017
    MONGO_CLIENT_USERNAME: root

    POSTGRES_CLIENT_HOST: postgresql
    POSTGRES_CLIENT_PORT: '5432'
    POSTGRES_CLIENT_USERNAME: postgres

    REDIS_CLIENT_HOST: redis-master
    REDIS_CLIENT_PORT: '6379'
    REDIS_URL: redis-master:6379

    BACKUP_CONTAINER_NAME: '{{ env.BACKUP_CONTAINER_NAME }}'
    BACKUPS_STORAGE_ACCOUNT_NAME: '{{ env.BACKUPS_STORAGE_ACCOUNT_NAME }}'

    # Misc
    UNLEASH_API_TOKEN: '{{ env.UNLEASH_API_TOKEN }}'

    DEFAULT_TIME_ZONE: Europe/Zagreb

  secrets:
    SENTRY_DSN: '{{ env.SENTRY_DSN }}'

    MONGO_CLIENT_PASSWORD: knopso123
    MONGO_URL: mongodb://root:knopso123@mongodb:27017
    POSTGRES_CLIENT_PASSWORD: knopso123

    BACKUPS_STORAGE_ACCOUNT_KEY: '{{ env.BACKUPS_STORAGE_ACCOUNT_KEY }}'
    BACKUPS_ZIP_ENCRYPT: '{{ env.BACKUPS_ZIP_ENCRYPT }}'

  backups:
    mongo:
      enabled: true
      cron: "3 5,17 * * *"
    postgres:
      enabled: true
      cron: "8 5,17 * * *"
    redis:
      enabled: true
      cron: "13 5,17 * * *"

  cecs:
    enabled: false
    params: "-e venv"

  repository: "nexus.vingd.net"

services:
  rule-engine:
    type: java
    resources:
      cpu: 500m
      memory: 650Mi


  heartbeat:
    type: python
    version: 5.0.0b0
    env:
      HEARTBEAT_CYCLE: 5
    db:
      mongo: true
    dependencies:
      - rule-engine-api==5.0.0b0
    resources:
      cpu: 69m
      memory: 65Mi
